# Generated by Django 3.2.2 on 2023-10-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0005_postimg_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MKSD_000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('file', models.FileField(upload_to='MKSD_000')),
            ],
        ),
        migrations.CreateModel(
            name='MKSD_LIVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('file', models.FileField(upload_to='MKSD_LIVE')),
            ],
        ),
        migrations.CreateModel(
            name='Neuigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('file', models.FileField(upload_to='Neuigkeit')),
            ],
        ),
    ]
