# Generated by Django 3.2.2 on 2023-10-27 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0007_auto_20231027_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mksd_000',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
