# Generated by Django 3.2.2 on 2023-10-27 17:48

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0008_alter_mksd_000_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuigkeit',
            old_name='date',
            new_name='neu_date',
        ),
        migrations.RenameField(
            model_name='neuigkeit',
            old_name='file',
            new_name='neu_file',
        ),
        migrations.RemoveField(
            model_name='neuigkeit',
            name='body',
        ),
        migrations.RemoveField(
            model_name='neuigkeit',
            name='name',
        ),
        migrations.AddField(
            model_name='neuigkeit',
            name='neu_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neuigkeit',
            name='neu_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mksd_000',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mksd_live',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
