# Generated by Django 3.2.2 on 2023-10-29 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0009_auto_20231027_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='neu_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('neu_image', models.ImageField(upload_to='neu_img/')),
            ],
        ),
        migrations.AddField(
            model_name='neuigkeit',
            name='neu_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
