# Generated by Django 3.2.2 on 2023-10-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0010_auto_20231029_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuigkeit',
            name='neu_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='mksd.neu_category'),
        ),
    ]
